version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            mkdir -p ~/bin
            curl -L -o ~/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x ~/bin/hadolint
            echo 'export PATH=$PATH:~/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run hadolint on Dockerfile
          command: hadolint Dockerfile

  build-app-karsajobs-ui:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push UI Docker Image
          command: |
            docker build -t ghcr.io/anril32/karsajobs-ui:latest .
            echo $CR_PAT | docker login ghcr.io -u anril32 --password-stdin
            docker push ghcr.io/anril32/karsajobs-ui:latest

workflows:
  karsajobs-ui-workflow:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui:
          requires:
            - lint-dockerfile
