version: 2.1

executors:
  golang-docker:
    docker:
      - image: cimg/go:1.21
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            mkdir -p ~/bin
            curl -L -o ~/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x ~/bin/hadolint
            echo 'export PATH=$PATH:~/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Run hadolint on Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: golang-docker
    steps:
      - checkout
      - run:
          name: Run Go unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t ghcr.io/anril32/karsajobs:latest .
            echo $CR_PAT | docker login ghcr.io -u anril32 --password-stdin
            docker push ghcr.io/anril32/karsajobs:latest

workflows:
  version: 2
  karsajobs-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - test-app
