version: 2.1

executors:
  golang-docker:
    docker:
      - image: cimg/go:1.21
  docker-executor:
    docker:
      - image: cimg/base:stable

jobs:
  lint-dockerfile:
    executor: docker-executor
    steps:
      - checkout
      - run:
          name: Install hadolint
          command: |
            curl -L -o /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
            chmod +x /usr/local/bin/hadolint
      - run:
          name: Run hadolint on Dockerfile
          command: hadolint Dockerfile

  test-app:
    executor: golang-docker
    steps:
      - checkout
      - run:
          name: Run Go unit tests
          command: go test -v -short --count=1 $(go list ./...)

  build-app-karsajobs:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t your-dockerhub-username/karsajobs:latest .
            echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push your-dockerhub-username/karsajobs:latest

workflows:
  version: 2
  karsajobs-workflow:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs:
          requires:
            - test-app
