# versi API yang digunakan
apiVersion: v1
# mengindikasikan resource yang digunakan
kind: Service
# berisi informasi yang relevan terkait resource dan membantu dalam pengidentifikasian
metadata:
  name: karsajobs-ui
  labels:
    app: karsa-jobs
# tempat kita menspesifikasikan resource
spec:
  # memakai tipe NodePort
  type: NodePort
  # mengekspos port
  ports:
    - port: 8000
  # menargetkan resource yang menggunakan service ini
  selector:
    tier: frontend
