# versi API yang digunakan
apiVersion: v1
# mengindikasikan resource yang digunakan
kind: PersistentVolume
# berisi informasi yang relevan terkait resource dan membantu dalam pengidentifikasian
metadata:
  name: rabbitmq-pv
  namespace: rabbitmq
  labels:
    type: local
# tempat kita menspesifikasikan resource
spec:
  # nama Storage Class dengan manual
  storageClassName: manual
  # kapasitas penyimpanan
  capacity:
    storage: 3Gi
  # access mode
  accessModes:
    # volume dapat dipasang sebagai read-write oleh satu node
    - ReadWriteOnce
  # Tempat menyimpan data
  hostPath:
    path: "/mnt/data/rabbitmq-data"
---
# versi API yang digunakan
apiVersion: v1
# mengindikasikan resource yang digunakan
kind: PersistentVolumeClaim
# berisi informasi yang relevan terkait resource dan membantu dalam pengidentifikasian
metadata:
  name: rabbitmq-pvc
  namespace: rabbitmq
# tempat kita menspesifikasikan resource
spec:
  # nama Storage Class dengan manual
  storageClassName: manual
  accessModes:
    # volume dapat dipasang sebagai read-write oleh satu node
    - ReadWriteOnce
  # permintaan penyimpanan
  resources:
    requests:
      storage: 3Gi
